config/routes.rb
Rails.application.routes.draw do
  	devise_for :members
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	root 'homes#top'
	  get 'homes/about'
    get 'member_show/:id' => 'members#show', as: 'member_show'
    get 'member_edit' => 'members#edit', as: 'member_edit'
    get 'member_blog/:id' => 'members#blog', as: 'member_blog'
    get 'member_photo/:id' => 'members#photo', as: 'member_photo'
  	resources :members, only: [:update] do
      get 'page/:page', :action => :index, :on => :collection
    end

  	resources :blogs do
      get :search, on: :collection
  		resources :post_comments, only: [:create, :destroy]
  		resource :favorites, only: [:create, :destroy]
  	end
  	resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	attachment :image
	belongs_to :member
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
  validates :image, presence: true
  validates :title, presence: true, length: { minimum: 1, maximum: 30 }
  validates :body, presence: true
  validates :category, presence: true

	def favorited_by?(member)
    return if member.blank?
    favorites.where(member_id: member.id).exists?
  end
  	enum category:{
    日常:   0, #日常
    食事:   1, #食事
    運動:   2, #運動
    病気:   3, #病気
    その他:  4 #その他
  }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :member
	belongs_to :blog
end

app/models/member.rb
class Member < ApplicationRecord
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    attachment :image
    has_many :blogs, dependent: :destroy
    has_many :photos, dependent: :destroy
    has_many :post_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    attachment :profile_image
end

app/models/photo.rb
class Photo < ApplicationRecord
	attachment :image
	belongs_to :member
	validates :image, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :member
	belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
    root_path # ログイン後に遷移するpath
  end
	def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email, :profile_image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:profile_image, :introduction, :name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def new
		@blog = Blog.new
	end

	def create
		@blog = Blog.new(blog_params)
		@blog.member_id = current_member.id
		if @blog.save
      flash[:notice] = "新規投稿が完了しました"
      redirect_to blog_path(@blog.id)
    else
   		flash[:alert] = "入力内容に誤りがあります"
   		render :new
  	end
	end

	def index
		@blogs = Blog.page(params[:page]).per(5).order(created_at: :desc)
	end

	def show
		@blog = Blog.find(params[:id])
    @post_comment = PostComment.new
    @member = @blog.member
    @post_comments = @blog.post_comments
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def update
		@blog = Blog.find(params[:id])
    if @blog.update(blog_params)
    	flash[:notice] = "Blogを更新しました"
     	redirect_to blog_path(@blog)
    else
    	flash[:alert] = "入力内容に誤りがあります"
     	render :edit
    end
	end

	def destroy
		blog = Blog.find(params[:id])
    if blog.destroy
    	flash[:notice] = "Blogを削除しました"
    	redirect_to blogs_path
    else
    	flash[:alert] = "Blogを削除できませんでした"
    	rende :show
    end
	end

	def search
		@blogs = Blog.page(params[:page]).per(5).order(created_at: :desc).joins(:member).select('blogs.*','members.name')
    if params[:word].present?
        @blogs = @blogs.where('name LIKE ? or title LIKE ? or body LIKE ?', "%#{params[:word]}%", "%#{params[:word]}%", "%#{params[:word]}%")
   	end

    if params[:category].present?
      @blogs = @blogs.where(category: params[:category])
  	end
  	  render :index
  end

	private
	def blog_params
      params.require(:blog).permit(:image, :title, :body, :category, :member_id )

  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :authenticate_member!
	def create
	    blog = Blog.find(params[:blog_id])
	    favorite = current_member.favorites.new(blog_id: blog.id)
	    favorite.save
	    redirect_to request.referer
    end

  	def destroy
		blog = Blog.find(params[:blog_id])
		favorite = current_member.favorites.find_by(blog_id: blog.id)
		favorite.destroy
		redirect_to request.referer
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
		@blogs = Blog.order(created_at: :desc).limit(4)
	end
	def about
		@random = Photo.all.sample(3)
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	def show
    	@member = Member.find(params[:id])
      @blogs = @member.blogs
      @photos = @member.photos
  	end

  	def edit
    	  @member = Member.find(current_member.id)
  	end

    def blog
      @member = Member.find(params[:id])
      @blogs = @member.blogs
    end

    def photo
      @member = Member.find(params[:id])
      @photos = @member.photos
    end

  	def update
    	@member = Member.find(params[:id])
    	if 	@member.update(member_params)
      		flash[:notice] = "登録情報を更新しました！"
      		redirect_to member_show_path(params[:id])
    	else
      		render :edit
      end
  	end
  	def member_params
    	params.require(:member).permit(:name, :email, :password, :introduction, :profile_image )
  	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def new
		@photo = Photo.new
	end

	def create
		@photo = Photo.new(photo_params)
		@photo.member_id = current_member.id
		if
			@photo.save
         	flash[:notice] = "新規投稿が完了しました"
         	redirect_to photo_path(@photo.id)
        else
         	flash[:alert] = "入力内容に誤りがあります"
         	render :new
        end
	end

	def index
		@photos = Photo.page(params[:page]).per(15).order(created_at: :desc)
	end

	def show
		@photo = Photo.find(params[:id])
        @member = @photo.member
	end

	def edit
		@photo = Photo.find(params[:id])
        if @photo.member.id != current_member.id
           redirect_to photos_path
        end
	end

	def update
		@photo = Photo.find(params[:id])
        if @photo.update(photo_params)
        	flash[:notice] = "Photoを更新しました"
         	redirect_to photo_path(@photo)
        else
        	flash[:alert] = "入力内容に誤りがあります"
         	render :edit
        end
	end

	def destroy
		photo = Photo.find(params[:id])
    if photo.destroy
    	flash[:notice] = "Photoを削除しました"
    	redirect_to photos_path
    else
    	flash[:alert] = "Photoを削除できませんでした"
    	rende :show
    end
	end

	private
	def photo_params
    params.require(:photo).permit(:image, :member_id )

  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :authenticate_member!
	def create
   		blog = Blog.find(params[:blog_id])
    	comment = current_member.post_comments.new(post_comment_params)
      comment.blog_id = blog.id
      if  comment.save
    	    redirect_to blog_path(blog)
      else
        redirect_to blog_path(blog), alert: 'コメントを入力してください'
      end
  end

	def destroy
  	PostComment.find_by(id: params[:id], blog_id: params[:blog_id]).destroy
  	redirect_to blog_path(params[:blog_id])
   end

  private
  def post_comment_params
    	params.require(:post_comment).permit(:comment, :blog_id ).merge(member_id: current_member.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/blogs/ search.html.erb
<h1 class="text-center">検索結果</h1>
<div class="blog">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'search', blogs: @blogs%>
		</div>
		<div class="col-lg-2"></div>
		<div class="col-lg-7">
			<%= render 'index', blogs: @blogs%>
		</div>
	</div>
</div>

app/views/blogs/_index.html.erb
<% blogs.each do |blog| %>
	<div class="blog-border">
	<div class="blog-border2"></div>
		<div class="row blogs">
			<div class="col-lg-3">
				<div class="blog-box">
					<table class="blog-table1">
						<tr>
							<th class="image-blog-index">
								<%= attachment_image_tag blog.member, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
							</th>
							<td><%= blog.member.name %></td>
						</tr>
					</table>
					<table class="blog-table2 pull-left">
						<tr>
							<th><h4><%= simple_format blog.title %></h4></th>
						</tr>
						<tr>
							<td><p class="overflow"><%= blog.body %></p>
							</td>
						</tr>
						<tr>
							<th class="blogs-category">#<%= blog.category %></th>
						</tr>
					</table>
				</div>
			</div>
			<div class="col-lg-4"></div>
			<div class="col-lg-3">
				<div class="blog-box2">
					<%= link_to blog_path(blog) do %>
						<%= attachment_image_tag blog, :image, size: "350x220" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/blogs/_search.html.erb
<div id="search">
	<h3 class="text-center" id="border"><i class="fas fa-search"></i>検索</h3>
	<div class="search-box"></div>
	<%= form_with url: search_blogs_path, method: :get, local: true do |f| %>
	  	<div class="form-group">
			<%= f.text_field :word, class: 'text-center form-control',placeholder:"キーワードを入力" %>
		</div>
	  	<div class="form-group text-center">
	  		<%= f.select :category, Blog.categories_i18n.keys.map {|k| [Blog.categories_i18n[k], k]}, { include_blank: 'カテゴリー検索'} %>
	 	</div>
		<div class="text-center">
			<%= f.submit :"検索", class: "btn btn--black btn--circle btn--circle-a btn--shadow" %>
		</div>
	<% end %>
</div>

app/views/blogs/edit.html.erb
<h1 class="text-center">Blog編集</h1>
<div class="container">
    <div class="row">
        <div class="col-lg-3">
        </div>
        <div class="col-lg-6 b-login">
            <div class="b-login2">
                <%= form_for(@blog) do |f| %>
                    <div class="form-group">
                       <%= f.label :image, '画像' %>
                       <%= f.attachment_field :image, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :title, 'タイトル' %>
                        <%= f.text_field :title, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :body, '本文' %>
                        <%= f.text_area :body, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :category, 'カテゴリー' %><br>
                        <%= f.select :category, Blog.categories_i18n.keys.map {|k| [Blog.categories_i18n[k], k]}, { include_blank: '必ず選択してください'} %>
                    </div>
                    <p class="text-center">
                        <%= f.submit '更新する', class: 'btn btn-primary btn btn--primary btn--radius btn--cubic'%>
                    </p>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/blogs/index.html.erb
<div class="text-center">
	<h1 class="text-center blog-text">Blog一覧</h1>
	<div class="photo-text2">
		<h4 class="text-center blog-text">(新着順)</h4>
	</div>
</div>
<div class="blog">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'search', blogs: @blogs%>
		</div>
		<div class="col-lg-1"></div>
		<div class="col-lg-7">
			<%= render 'index', blogs: @blogs%>
		</div>
	</div>
</div>
<%= paginate @blogs %>

app/views/blogs/new.html.erb
<body>
    <h1 class="text-center" id="new">Blog投稿</h1>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
            </div>
            <div class="col-lg-6 b-login">
                <div class="b-login2">
                    <%= form_for(@blog) do |f| %>
                        <div class="item-image">
                        <%= attachment_image_tag @blog, :image, id: "img_prev", fallback: "no_image.jpg", size:"350x200" %>
                        </div>
                        <div class="form-group">
                           <%= f.label :image, '画像' %>
                           <%= f.attachment_field :image, class: 'form-control input-lg', id: "blog_image" %>
                        </div>
                        <div class="form-group">
                            <%= f.label :title, 'タイトル' %>
                            <%= f.text_field :title, placeholder:"30文字以下で入力してください", class: 'form-control'  %>
                        </div>
                        <div class="form-group">
                            <%= f.label :body, '本文' %>
                            <%= f.text_area :body,placeholder:"入力してください", class: 'form-control' %>
                        </div>
                        <div class="form-group">
                            <%= f.label :category, 'カテゴリー' %><br>
                            <%= f.select :category, Blog.categories_i18n.keys.map {|k| [Blog.categories_i18n[k], k]}, { include_blank: '必ず選択してください'} %>
                        </div>
                        <p class="text-center new2">
                            <%= f.submit '投稿する', class: "btn btn--blue btn--border-outset" %>
                        </p>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/blogs/show.html.erb
<div class="container">
	<div class="row">
		<div class="blog-show"></div>
		<h1 class="text-center">Blog詳細</h1>
		<div class="col-lg-4"></div>
		<div class="col-lg-5">
			<table>
				<tr>
					<th class="image-blog-show">
						<%= link_to member_show_path(@member) do %>
							<%= attachment_image_tag @blog.member, :profile_image, size: "50x50", fallback: "no_image.jpg" %>
						<% end %>
					</th>
					<th><%= @blog.member.name %></th>
				</tr>
			</table>
			<table>
				<tr>
					<th>
						<th><h4><%= simple_format @blog.title %></h4></th>
					</th>
				</tr>
			</table>
			<p>
				<%= attachment_image_tag @blog , :image, size: "450x300"  %>
			</p>
			<p class="pull-right">
				<% if current_member.present? && @blog.member.id == current_member.id %>
					<%= link_to "編集する", edit_blog_path(@blog), class: 'btn btn-primary btn btn--primary btn--radius btn--cubic' %>

					<%= link_to "削除する", blog_path(@blog), class:'btn btn-danger btn btn--red btn--radius btn--cubic',  method: :delete, data: {confirm: "削除しますか？"} %>
			  	<% end %>
		  	</p>
			<% if current_member.present? %>
				<% if @blog.favorited_by?(current_member) %>
					<p>
						<%= link_to blog_favorites_path(@blog), method: :delete do %>
							<span style="font-size: 30px">
						    	<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
						    </span>
						    <%= @blog.favorites.count %>
						<% end %>
					</p>
				<% else %>
					<p>
				 		<%= link_to blog_favorites_path(@blog), method: :post do %>
				    		<span class="glyphicon glyphicon-heart" aria-hidden="true"style="font-size: 30px"></span>
				   			<%= @blog.favorites.count %>
				  		<% end %>
					</p>
				<% end %>
			<% else %>
				<p>
		    		<span class="glyphicon glyphicon-heart" aria-hidden="true"style="font-size: 30px"></span>
		   			<%= @blog.favorites.count %>
				</p>
			<% end %>
			<table class="blog-body-table">
					<tr>
						<th><%= simple_format @blog.body %></th>
					</tr>
			</table>
			<table>

					<tr>
						<th class="blog-category">#<%= @blog.category %></th>
					</tr>
				</tbody>
			</table>
			<p class="comments-count">
				<a href="#comments">コメント数 :<%= @blog.post_comments.count %>件</a>
			</p>
			<% if member_signed_in? %>
				<div class="comment-form">
					<%= form_for [@blog, @post_comment] do |f| %>
						<div class="form-group">
	      					<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
	      				</div>
	      				<div class="text-right">
	      					<%= f.submit "送信", class: "btn-default btn btn--silver btn--radius btn--cubic" %>
	      				</div>
					<% end %>
				</div>
			<% else %>
				<h3>　※いいねとコメントには登録が必要です</h3>
				<p class="text-center">
					<%= link_to '新規登録はこちら',new_member_registration_path, class: 'fas fa-user-plus btn btn--kyosuke btn-c' %>
				</p>
			<% end %>
			<table class="post-comment">
				<% @post_comments.each do |post_comment| %>
					<tr>
						<td class="image-comment">
							<%= attachment_image_tag post_comment.member , :profile_image, size: "40x40", fallback: "no_image.jpg" %>
						</td>
						<td class="post-comment2">
							<%= post_comment.comment %>
						</td>
						<% if post_comment.member == current_member %>
							<td>
								<%= link_to "削除",  blog_post_comment_path(@blog,post_comment),class:'btn btn-danger btn btn--red btn--radius btn--cubic',method: :delete, "data-confirm" => "本当に削除しますか？" %>
							</td>
						<% end %>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/homes/about.html.erb
<div class="container">
	<div class="row">
		<div class="about">
			<div class="about-box2">
				<div class="mini">
					<h2 class="text-center">~サイト概要~</h2>
					<p class="text-center about-text">
						このサイトは、犬を飼っている方や犬が好きな方、
					</p>
					<p class="text-center">
						これから犬を買おうとしている人などに向け	情報共有サイトとなっております！
					</p>
					<p class="text-center">
						自分の家族でもある犬の貴重な一瞬を記録し、共有しませんか？
					</p>
					</p>
				</div>
				<div class="about-img">
						<%= attachment_image_tag @random[0], :image,size: "585x280" %>
				</div>
			</div>
			<div class="about-box3">
				<div class="mini2">
						<%= attachment_image_tag @random[1], :image,size: "585x280" %>
				</div>
				<div class="about-img2">
					<h2 class="text-center about-tx">~ブログと画像投稿~</h2>
					<p class="text-center about-text2">																			犬との生活で可愛い一面、何気ない日常など、
					</p>
					<p class="text-center">
						そして悩みや、他の飼い主さんや犬が好きな方に共有したいことをブログに
					</p>
					<p class="text-center">
						犬の一瞬を切り取ったベストショットを画像投稿へ
					</p>
				</div>
			</div>
			<div class="about-box4">
				<div class="mini3">
					<h2 class="text-center about-tx">~犬が家族の一員になるということ~</h2>
					<p class="text-center about-text2">
						犬を家族に迎えた人の中には、人生が大きく変わったという人もいます
					</p>
					<p class="text-center">
						「人生のどん底にいた自分をこのコは救ってくれた」「このコは大切なパートナー！」と、
					</p>
					<p class="text-center">
					犬がいない人生は考えられないとまで言う人も少なくありません。
					</p>
					<p class="text-center">
					犬がそこまで愛されるのはどうしてなのでしょうか？
					</p>
					<p class="text-center">
						このサイトを通じて犬との生活をより良いものへ
					</p>
				</div>
				<div class="about-img3">
					<%= attachment_image_tag @random[2], :image,size: "585x280" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/homes/top.html.erb
<div class="container">
	<div class="row top">
		<div id="theTarget">
		    <div class="top-img ti" style="background-image: url('<%= asset_path("shinamon2.jpg") %>');"><h1 class="text-center top-img2">Welcome to dog_blog</h1></div>
		    <div class="top-img" style="background-image: url('<%= asset_path("dog3.jpg") %>');"></div>
		    <div class="top-img" style="background-image: url('<%= asset_path("dog4.jpg") %>');"></div>
		    <div class="top-img" style="background-image: url('<%= asset_path("dog2.jpg") %>');"></div>
		    <div class="top-img" style="background-image: url('<%= asset_path("dog7.jpg") %>');"></div>
		    <div class="top-img" style="background-image: url('<%= asset_path("dog8.jpg") %>');"></div>
		    <div class="top-img" style="background-image: url('<%= asset_path("dog9.jpg") %>');"></div>
		 </div>
	</div>
	<div>
		<h1 class="text-center" id="top-text">~Blog新着~</h1>
		<table class="table-hover top-table">
			<% @blogs.each do |blog| %>
				<tbody id="top-b">
					<tr>
						<td id="top-member">
							<%= link_to blog_path(blog) do %>
								<%= attachment_image_tag blog.member, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td id="m-title">
							<h4 class="text-center">
								<%= link_to blog_path(blog) do %>
									<%= blog.title %>
								<% end %>
								</h4>
							</td>
						<td><%= blog.created_at.strftime('%Y/%m/%d') %></td>
					</tr>
				</tbody>
			<% end %>
		</table>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>DogBlog</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <script src="https://kit.fontawesome.com/ee8e77f5d3.js" crossorigin="anonymous"></script>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <div class="container">
        <nav>
          <nav class="nav navbar-nav navbar-left">
              <%= link_to root_path do %>
                  <span class="header-title">Dog<span class="color"><i class="fas fa-paw"></i></span>Blog</span>
              <% end %>
          </nav>
          <ul class="nav navbar-nav navbar-right">
            <% if member_signed_in? %>
              <li class="header-text">
                <%= link_to "マイページ",member_show_path(current_member.id), class: 'header-text' %>
              </li>
              <li>
                <%= link_to "About",homes_about_path, class: 'header-text' %>
              </li>
              <li role="presentation" class="dropdown">
                <a class="dropdown-toggle header-text" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                  投稿一覧<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li role="presentation"><%= link_to "Blogs",blogs_path, class: 'header-text' %></li>
                  <li role="presentation"><%= link_to "Photos",photos_path, class: 'header-text' %></li>
                </ul>
              </li>
              <li role="presentation" class="dropdown">
                <a class="dropdown-toggle header-text" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                  新規投稿<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li role="presentation"><%= link_to "Blog投稿",new_blog_path, class: 'header-text' %></li>
                  <li role="presentation"><%= link_to "Photo投稿",new_photo_path, class: 'header-text' %></li>
                </ul>
              </li>
              <li>
                <%= link_to "Log out",destroy_member_session_path, class: 'header-text', method: :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to "Home",root_path, class: 'header-text' %>
              </li>
              <li>
                <%= link_to "About",homes_about_path, class: 'header-text' %>
              </li>
              <li role="presentation" class="dropdown">
                <a class="dropdown-toggle header-text" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                  投稿一覧<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li role="presentation"><%= link_to "Blogs",blogs_path, class: 'header-text' %></li>
                  <li role="presentation"><%= link_to "Photos",photos_path, class: 'header-text' %></li>
                </ul>
              </li>
              <li>
                <%= link_to "新規登録",new_member_registration_path, class: 'header-text' %>
              </li>
              <li>
                <%= link_to "ログイン",new_member_session_path, class: 'header-text' %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <div class="row">
        <% if notice %>
          <p id="validate"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger" id="validate"><%= alert %></p>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <footer>
      <p>© All rights reserved by dog_blog</p>
    </footer>
  </body>
</html>

app/views/members/blog.html.erb
<h1 class="text-center m-text">Blog一覧</h1>
<div class="container" id="member_b" >
	<div class="row">
		<%= render 'blogs/index', blogs: @blogs%>
	</div>
</div>

app/views/members/edit.html.erb
<h1 class="text-center">プロフィール編集</h1>
<div class="container">
    <div class="row">
        <div class="col-lg-3">
        </div>
        <div class="col-lg-6">
            <%= form_for(@member) do |f| %>
                <div class="form-group">
                   <%= f.label :profile_image, '画像' %>
                   <%= f.attachment_field :profile_image, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :name, '名前' %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :introduction, 'ひとこと' %>
                    <%= f.text_area :introduction, class: 'form-control' %>
                </div>
                <p class="text-center">
                    <%= f.submit '更新', class: 'btn btn-success btn btn--success btn--radius btn--cubic' %>
                </p>
            <% end %>
        </div>
    </div>
</div>

app/views/members/photo.html.erb
<h1 class="text-center m-text">Photo一覧</h1>
<div class="container" id="member_b" >
	<div class="row">
		<%= render 'photos/index', photos: @photos%>
	</div>
</div>

app/views/members/show.html.erb
<div id="myshow">
    <h1 class="text-center myshow">マイページ</h1>
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <p class="image-member-show">
                    <%= attachment_image_tag @member, :profile_image, fallback: "no_image.jpg", size: "300x300"  %>
                </p>
            </div>
            <div class="col-lg-7">
                <table class="table">
                    <tr>
                        <th>ニックネーム</th>
                        <td><%= @member.name %></td>
                    </tr>
                    <tr>
                        <th>ひとこと</th>
                        <td>
                            <%= simple_format @member.introduction %>
                        </td>
                    </tr>
                    <tr>
                        <th>Blogs</th>
                        <td>投稿
                            <%= link_to member_blog_path(@member.id) do %>
                            <%= @blogs.count %>
                            <% end %>件
                        </td>
                    </tr>
                    <tr>
                        <th>Photos</th>
                        <td>投稿
                            <%= link_to member_photo_path(@member.id) do %>
                            <%= @photos.count %>
                            <% end %>件
                        </td>
                    </tr>
                </table>
                <% if @member.id == current_member.id %>
                    <p class="pull-right">
                        <%= link_to "編集", member_edit_path(id: current_member.id), class: 'btn btn-primary btn btn--primary btn--radius btn--cubic' %>
                    </p>
                <% end %>
            </div>
        </div>
    </div>
</body>